### ISSUE TITLE
Never actually posts anything - possible coding logic error

### ISSUE THREAD

**Issue by bhulk** [AkitotheExiled/RSSReply#8]
Following all instructions perfectly, the script keeps looping and trying to pull from RSS feeds but never logically steps into the posting of the article because it is buried in the "if not does_exist" statement - which it never reaches. 

Anyone else having this issue?

**Comment by AkitotheExiled** [comment]
What RSS Feed are you attempting to pull from?

**Comment by AkitotheExiled** [comment]
@bhulk I've tried the following,

Using the following RSS Feed
> http://pix.adoreanime.com/pixiv/search/vocaloid/other/safe

1. I've run the program exactly one time and was prompted with,

> Article Exists? -> False
Article: (Summerミクちゃん🌊🌴✨, https://www.pixiv.net/artworks/99061400) posted in subreddit with flairid


2. Article is inserted into the database
> ![image](https://user-images.githubusercontent.com/20932882/173695257-c0b0b4e8-0f45-4fc6-b2b1-6cb623c3367e.png)

3. Subsequent reruns give me the following,
> Article: Summerミクちゃん🌊🌴✨, already exists in the database/subreddit!
Waiting 40 seconds before attempting to pull next subreddit/article.

The program should continue like that until the RSS Feed gets updated and a new article replaces the Summerミクちゃん🌊🌴✨one.  Then, the steps 1-3 repeat itself.

I'll rewrite the if statement for does not exist as its redundant.  I'm also closing this issue as is.

**Comment by AkitotheExiled** [comment]
Rewrote the logic for posting/retrieving. Checkout the latest commit @bhulk
